config/routes.rb
Rails.application.routes.draw do  
  
  
  resources :dishes

  resources :orders do
    resources :dishes do
      member do 
        delete "popDish"
      end
    end
  end
  get 'orders/add/:id2' => 'orders#add', as: :add
  get 'orders/estado/:id' => 'orders#estado', as: :estado
  
  devise_for :users, controllers:{\
    omniauth_callbacks: "users/omniauth_callbacks"\
  }
  devise_scope :users do
    get 'users', to: 'users#index'
  end

  resources :users

  root 'orders#new'

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :details, :dependent => :destroy
  has_many :dishes, :through => :details
  belongs_to :user

  attr_accessor :cuenta, :suma
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	layout 'bootstrap'

	def index
		#@orders = Order.all.includes(:dishes)
		@mis_ordenes = Order.all.includes(:dishes)
		@mis_ordenes.each do |orden|
		orden.cuenta = Order.find(orden.id).dishes.group("name").count
		orden.suma = Order.find(orden.id).dishes.sum("price")
		end		
	end

	def new
		@dishes = Dish.all
	end

	def create
		@order = Order.new()
		@order.user_id = current_user.id
		@order.save
		@order.dishes << Dish.find(params[:dish_id])
		redirect_to	edit_order_path(@order)
	end

	def edit
		@orders = Order.find(params[:id]).dishes.group("name").count
		@suma = Order.find(params[:id]).dishes.sum("price")
		@dishes = Dish.all
		@order_id = Order.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])
		@order.dishes << Dish.find(params[:dish_id])
		@order.save
		redirect_to	edit_order_path(@order)		
	end

	def estado
		@order = Order.find(params[:id])
		if @order.condition.nil?
			@order.condition = "cocina"
		else
		 @order.condition = params[:order][:condition]
		end
		@order.save
		redirect_to orders_path
	end

	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		redirect_to	orders_url
	end

	
	def order_params
		params.require(:order).permit(:title, :content, :created_at, :condition)
	end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1> Pedido actual </h1>
<% @orders.each do |dish, cuenta| %>
	<p> <%= dish %> (<%= cuenta %>) </p>
<% end %>

<p>Total = <%= @suma %></p>

<h1>Agregar Plato</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-2" id="order-list" style="display:none"></div>
</div>

<%= render 'form' %>
<%= render :partial => 'dishes/dishesToOrders', collection:  @dishes, as: :dish, locals: {
	order: @order}  %>
<%= link_to 'Cerrar Pedido', estado_path %>
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if user_signed_in? %>
    <% @mis_ordenes.each do |orden| %>
    	<div class="jumbotron">
	    	<div class="container">
	      		<h3><%= orden.id %></h3>
	      		<% orden.cuenta.each do |clave, valor| %>
	      			<%= clave %> x<%= valor %><br>
	      		<% end %>
	      		<%= orden.condition %><br>
	      		Total = $<%= orden.suma %>
	      		<%= form_for orden, url: estado_path(orden), method: :get do |f| %>
	      			<%= f.select :condition, options_for_select([["-----","nil"],["Cocina","cocina"],["Despachado","despachado"],["Pagado","pagado"]]) %>
	      			<%= f.submit "actualizar" %>
	      		<% end  %>
	      		<td><%= link_to 'Destroy', orden, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
	      	</div>
      	</div>
    <% end %>
 <% end %>

app/views/orders/new.html.erb
<% if user_signed_in? %>
	<h1>Agregar Plato</h1>
	<div class="row">
	  <div class="col-md-6 col-md-offset-2" id="order-list" style="display:none"></div>
	</div>

	<%= render 'form' %>
	<%= render :partial => 'dishes/dishesToOrders', collection:  @dishes, as: :dish, locals: {
		order: @order}  %>
	<%= link_to 'Back', orders_path %>
<% else  %>
	<%= link_to 'Ingresar', new_user_session_path %>
<% end  %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/updeate.html.erb
<h1>Orders#updeate</h1>
<p>Find me in app/views/orders/updeate.html.erb</p>