config/routes.rb
Rails.application.routes.draw do  
  
  
  resources :dishes

  resources :orders do
    resources :dishes do
      member do 
        delete "popDish"
      end
    end
  end
  get 'orders/add/:id2' => 'orders#add', as: :add
  get 'orders/estado/:id' => 'orders#estado', as: :estado
  
  devise_for :users, controllers:{\
    omniauth_callbacks: "users/omniauth_callbacks"\
  }
  devise_scope :users do
    get 'users', to: 'users#index'
  end

  resources :users

  root 'orders#new'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	has_many :details, :dependent => :destroy
	has_many :orders, :through => :details
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :all_dishes, only: [:index, :create, :update, :destroy]
  before_action :set_dishes, only:[:edit,:update, :destroy, :show]
  respond_to :js
  layout 'bootstrap'

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.create(dish_params)    
  end

  def update
   @dish.update_attributes(dish_params)
  end

 def destroy
  @dish.destroy
end

def show
end

def popDish
  detail = Detail.where(order_id: params[:id]).where(dish_id: params[:dish_id]).first
  if detail
    detail.destroy
  end
  redirect_to edit_order_path(params[:id])
end

private

def all_dishes
  @dishes = Dish.all
end

def set_dishes
  @dish = Dish.find(params[:id])
end

def dish_params
  params.require(:dish).permit(:name, :price, :description)
end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<li class="list-group-item list-group-item-info">
  <%= dish.description %>
  <%= dish.name %>
  <span class=""><%= dish.price.to_s %></span>

  <span class="edit">


    <%= link_to edit_dish_path(dish), remote: true do %>
      <button class="btn btn-primary btn-xs">Edit</button>
    <% end %>

    
    <%= link_to dish, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } do %>
      <button class="btn btn-danger btn-xs">Delete!</button>
    <% end %>
  </span>
</li>

app/views/dishes/_dishesToOrders.html.erb
<li class="list-group-item list-group-item-info">
  <%= dish.description %>
  <%= dish.name %>
  <span class=""><%= dish.price.to_s %></span>
  <% if @order_id.nil? %>
	  <%= link_to "Agregar", orders_path(dish_id: dish.id), method: :post, class: 'btn btn-primary' %>
  <% else %>
	  <%= link_to "Agregar", order_path(dish_id: dish.id), method: :patch, class: 'btn btn-primary' %>
	  <%= link_to "Eliminar", popDish_order_dish_path(order_id: @order_id, dish_id: dish.id), method: :delete, class: 'btn btn-primary' %>
  <% end %>
</li>

app/views/dishes/_form.html.erb
<div class="container">
	<div class="col-xs-2 col-sm-2 col-md-2">
		<%= simple_form_for(@dish, remote: true, html: { class: 'form-horizontal'}) do |f|%>
		<div class="form-inputs">
			<%= f.input :name, requiered: true, autofocus: true, label:false, placeholder: 'Nombre' %>
			<%= f.input :description, requiered:true, label:false, placeholder: 'Descripcion', as: :text %>
			<%= f.input :price, requiered: true, label:false, placeholder: 'Precio' %>
			<%= f.button :submit %>
		<% end %>
		</br>
	</div>
</div>
</div>

app/views/dishes/create.js.erb
$('#dishes').html("<%= j (render @dishes) %>");
$('#dish-form').slideUp(350);

app/views/dishes/destroy.js.erb
$('#dishes').html("<%= escape_javascript(render @dishes) %>");

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/edit.js.erb
$('#dish-form').html("<%= escape_javascript(render 'form') %>");
$('#dish-form').slideDown(350);

app/views/dishes/index.html.erb
  <div class="col-md-5 col-md-offset-1">
    <h2>Dishes</h2>
  </div>
  <% if can? :new, @dish %>
<div class="row">
  <div class="col-md-2 col-md-offset-1">
    <%= link_to new_dish_path, remote: true do %>
      <button class="btn btn-primary">New</button>
    <% end %>
  </div>
</div>
<% end %>
  
<div class="row">
  <div class="col-md-6 col-md-offset-2" id="dish-form" style="display:none"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="dishes"><%= render @dishes %></div>
</div>
<script>

</script>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/new.js.erb
$('#dish-form').html("<%= j (render 'form')%>");
$('#dish-form').slideDown(350);

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/update.js.erb
$('#dishes').html("<%= escape_javascript(render @dishes) %>");
$('#dish-form').slideUp(350);