config/routes.rb
Rails.application.routes.draw do  
  
  
  resources :dishes

  resources :orders do
    resources :dishes do
      member do 
        delete "popDish"
      end
    end
  end
  get 'orders/add/:id2' => 'orders#add', as: :add
  get 'orders/estado/:id' => 'orders#estado', as: :estado
  
  devise_for :users, controllers:{\
    omniauth_callbacks: "users/omniauth_callbacks"\
  }
  devise_scope :users do
    get 'users', to: 'users#index'
  end

  resources :users

  root 'orders#new'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation" >
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>
				El Jamon Palta Pro
			</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<p class="navbar-text"><%= image_tag current_user.photo %>  Hola <%= current_user.name %> | estas logeado como: <%= current_user.role %> | <%= link_to("Log out", destroy_user_session_path, method: :delete) %></p>				
				<% else %>
				<p class="navbar-text"><%= link_to "Sign in", new_user_session_path %></p>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="col-sm-2 sidebar">
	<!-- sidebar content muestra en el titulo como el nombre del controlador actual esto esta seteado en aplication_controller -->
	<ul class="nav nav-sidebar">
		<li class="<%= @controllerName == 'Dishe' ? 'active' : '' %>"><%= link_to 'Platos', dishes_path %></li>
		<li class="<%= @controllerName == 'Order' ? 'active' : '' %>"><%= link_to 'Pedido', orders_path %></li>
		<li class="<%= @controllerName == 'User' ? 'active' : '' %>"><%= link_to 'Usuarios', users_path %></li>
	</ul>
</div>

app/views/layouts/_tabs.html.erb
<div class="row">
	<div class="col-xs-12">
		<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end -%>
	</div>
</div>

<!--Esto es lo que renderea los tabs desde cada uno de los controladores en cualquiera de sus acciones -->	
<ul class="nav nav-tabs" role="tablist">
	<li class=<%= @acctionName == "index" ? "active" : "" %>><%= link_to 'View list',
	controller: @controllerName.downcase.pluralize %></li>
	<li class=<%= @acctionName == "new" ? "active" : "" %>><%= link_to "New #{@controllerName.to_s.downcase}",controller: @controllerName.downcase.pluralize, action: 'new' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Restorant</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<style>
body {
	background:url(<%=asset_path '1.jpg'%>)no-repeat left top;
	background-size: 100%;
}
</style>
<body>
	<div id="main-container" class="container">
		<div class="row">
			<%=  render 'shared/facebook_sdk' %>
		
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restorant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
	<div id="main-container" class="container-fluid">
		<div class="row">
			<%= render 'layouts/sidebar'%>
			<div id="content" class="col-sm-10">
				<%= render 'layouts/tabs'%>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>